
// for user
###
GET http://localhost:8000/api/v1/question_paper/cq?classes="12"&bookName="Bangla_2st_paper"&chapter="2"
###
GET http://localhost:8000/api/v1/question_paper/mcq

//question create
###
POST http://localhost:8000/api/v1/mcq_1/questions
Content-Type: application/json

{
    "serial":"1",
    "question": "whats your father name",
    "classes": "12",
    "bookName": "Bangla_2st_paper",
    "chapter":"2",
    "type":"hard",
    "answer":"option_d",
    "option_a":"korim",
    "option_b":"salam",
    "option_c":"borkot",
    "option_d":"aklas"
}

//get all question
###
GET http://localhost:8000/api/v1/mcq_1/questions/12

//get single question
###
GET http://localhost:8000/api/v1/mcq_1/questions/12/d_LSuTEOI
//delete single question
###
DELETE  http://localhost:8000/api/v1/mcq_1/questions/12/d_LSuTEOI
//create user
###

//question create
POST http://localhost:8000/api/v1/mcq_2/questions
Content-Type: application/json

{
    "serial":"1",
    "classes": "12",
    "bookName": "Bangla_2st_paper",
    "chapter":"2",
    "type":"hard",
    "question": "whats your father name",
    "question_i":"korim",
    "question_ii":"solim",
    "question_iii":"ahmed",
    "option_a":"i & ii",
    "option_b":"i",
    "option_c":"iii",
    "option_d":"ii",
    "answer":"option_a"
}

//get all question
###
GET http://localhost:8000/api/v1/mcq_2/questions/12

//get single question
###
GET http://localhost:8000/api/v1/mcq_2/questions/12/78MWlMLAd
//delete single question
###
DELETE  http://localhost:8000/api/v1/mcq_2/questions/12/78MWlMLAd
//create user
###

//question create
POST http://localhost:8000/api/v1/mcq_3/questions
Content-Type: application/json

{
    "serial":"1",
    "classes": "12",
    "bookName": "Bangla_2st_paper",
    "chapter":"2",
    "type":"hard",
    "image":"link",
    "question": "whats your father name",
    "question_i":"korim",
    "question_ii":"solim",
    "question_iii":"ahmed",
    "option_a":"i & ii",
    "option_b":"i",
    "option_c":"iii",
    "option_d":"ii",
    "answer":"option_a"
}

//get all question
###
GET http://localhost:8000/api/v1/mcq_3/questions/12

//get single question
###
GET http://localhost:8000/api/v1/mcq_3/questions/12/78MWlMLAd
//delete single question
###
DELETE  http://localhost:8000/api/v1/mcq_3/questions/12/78MWlMLAd
//create user
###
//question create
POST http://localhost:8000/api/v1/mcq_4/questions
Content-Type: application/json

{
    "serial":"1",
    "classes": "12",
    "bookName": "Bangla_2st_paper",
    "chapter":"2",
    "type":"hard",
    "oddipok": "whats your father name",
    "question": "whats your father name",
    "option_a":"korim",
    "option_b":"salam",
    "option_c":"borkot",
    "option_d":"aklas",
    "answer":"option_d"
}

//get all question
###
GET http://localhost:8000/api/v1/mcq_4/questions/12

//get single question
###
GET http://localhost:8000/api/v1/mcq_4/questions/12/Fe82WQCtQ
//delete single question
###
DELETE  http://localhost:8000/api/v1/mcq_4/questions/12/Fe82WQCtQ
//create user
###

//question create cq
POST http://localhost:8000/api/v1/cq/questions
Content-Type: application/json

{
    "serial":"1",
    "oddipok": "whats your father name",
    "classes": "12",
    "bookName": "Bangla_2st_paper",
    "chapter":"2",
    "type":"hard",
    "question_a":"whats your name",
     "question_b":"whats your father name",
   "question_c":"whats your mother name",
     "question_d":"whats your gf name",
    "answer_a":"aklas",
    "answer_b":"aklas",
    "answer_c":"aklas",
    "answer_d":"aklas"
}

//get all question
###
GET http://localhost:8000/api/v1/cq/questions/12

//get single question
###
GET http://localhost:8000/api/v1/cq/questions/12/g1GuRGN0I
//delete single question
###
DELETE  http://localhost:8000/api/v1/cq/questions/12/g1GuRGN0I
//create user
###
POST http://localhost:8000/api/v1/users/register
Content-Type: application/json

{
    "name":"aymon",
    "email":"aymon6@gmail.com",
    "password":"22883377",
    "instituteName":"ideal cosing center",
    "service":"1",
    "status":"unblock",
    "role":"Users",
    "ipAddress":"110112.00"
}

//block user
###

PATCH  http://localhost:8000/api/v1/users/block/-RzHpxdlm
###
//delete user
DELETE   http://localhost:8000/api/v1/users/5jhWeNebF

// update user
###
PATCH  http://localhost:8000/api/v1/users/6F_lXVz-I
Content-Type: application/json

{
    
    "name":"",
    "email":"",
    "password":"",
    "institueName":"",
    "service":"",
    "role":"",
    "ipAddress":""
}
// get a single user
###
GET http://localhost:8000/api/v1/users/NRbScTAS_
// get all user
###
GET http://localhost:8000/api/v1/users
